apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  labels:
    release: monitoring
  name: titanic
spec:
  endpoints:

  - path: /metrics
    port: titanic
    scheme: http
    interval: 60s

  jobLabel: titanic
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: titanic